apiVersion: v1
kind: pod
metadata:
  name: multi-container

spec:
  containers:
    - name: nginx
      image: nginx
      ports:
       - 80 : 80
    - name: almalinux
      image: almalinux:8
      command: ["sleep", "3000"]

      
