apiVersion: v1
kind: pod
metadata: 
  name: resource_request_limits
spec:
  containers:
  - name: my-app
    image: nginx
    resources:
      request: 
        memory: "256mi" # Minimum memory request
        cpu: "250m"     # Minimum CPU request (0.25 CPU)
      limits: 
        memory: "512mi"     # Maximum memory limit
        cpu: "500m"         # Maximum CPU limit (0.5 CPU)


     